language: php
sudo: false
php:
  - '7.2.1'

install:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - vendor/bin/phpunit