# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AppBundle\:
    resource: '../../src/AppBundle/*'
    exclude: '../../src/AppBundle/{Entity,Repository}'

  AppBundle\Command\UpdateOldTasksCommand:
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      -  { name: console.command }

  AppBundle\Command\LoadFixturesCommand:
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      -  { name: console.command }

  AppBundle\Form\UserType:
    arguments: ['%security.role_hierarchy.roles%']
    tags: ['form.type']

  AppBundle\Service\TwigDateRequestListener:
    arguments: ["@twig"]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  AppBundle\DoctrineListener\UserSubscriber:
    arguments:
      - '@security.password_encoder'
    tags:
      - { name: doctrine.event_subscriber, connection: default }
